commit

diff --git a/.github/workflows/rocprofiler-compute-formatting.yml b/.github/workflows/rocprofiler-compute-formatting.yml
--- a/.github/workflows/rocprofiler-compute-formatting.yml
+++ b/.github/workflows/rocprofiler-compute-formatting.yml
@@ -10,6 +10,15 @@ on:
     paths:
       - '.github/workflows/rocprofiler-compute-formatting.yml'
       - 'projects/rocprofiler-compute/**'
+      - '!**/*.md'
+      - '!**/*.rtf'
+      - '!**/*.rst'
+      - '!**/.markdownlint-ci2.yaml'
+      - '!**/.readthedocs.yaml'
+      - '!**/.spellcheck.local.yaml'
+      - '!**/.wordlist.txt'
+      - '!docs/**'
+      - '!projects/*/docs/**'
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
@@ -32,7 +41,7 @@ jobs:
       working-directory: projects/rocprofiler-compute
       run: |
         python -m pip install --upgrade pip
-        python -m pip install ruff
+        python -m pip install ruff==0.14.11
         if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
     - name: Run Ruff Linter and Import Sorter
       run: |
@@ -73,6 +82,33 @@ jobs:
         gersemi -i $(find . -type f | egrep 'CMakeLists.txt|\.cmake$')
         if [ $(git diff | wc -l) -gt 0 ]; then
           echo -e "\nError! CMake code not formatted. Run gersemi...\n"
+          echo -e "\nFiles:\n"
+          git diff --name-only
+          echo -e "\nFull diff:\n"
+          git diff
+          exit 1
+        fi
+
+  cxx:
+    runs-on: ubuntu-22.04
+
+    steps:
+    - uses: actions/checkout@v4
+      with:
+        sparse-checkout: projects/rocprofiler-compute
+    - name: Install dependencies
+      working-directory: projects/rocprofiler-compute
+      run: |
+        sudo apt-get update
+        sudo apt-get install -y python3-pip
+        python3 -m pip install clang-format
+    - name: clang-format
+      working-directory: projects/rocprofiler-compute
+      run: |
+        set +e
+        clang-format -i $(find src -type f | egrep '\.(h|hpp|hh|c|cc|cpp)(|\.in)$')
+        if [ $(git diff | wc -l) -gt 0 ]; then
+          echo -e "\nError! cxx code not formatted. Run clang-format...\n"
           echo -e "\nFiles:\n"
           git diff --name-only
           echo -e "\nFull diff:\n"
